default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  encoding: utf8
  username: <%= ENV['DB_USER_NAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST_NAME'] %>

development:
  <<: *default
  database: db/push_sample_development

test:
  <<: *default
  database: db/push_sample_test

production:
  <<: *default
  database: db/push_sample_production
